language: python
python:
  - 2.7
  - 3.8
addons:
  apt:
    update: true
    packages:
      - libnl-3-dev
      - libnl-genl-3-dev
install: pip install flake8
before_script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script: python setup.py install
